package neighbors.enums.bot;

public enum State {
    NEW_USER,
    REGISTRATION,
    DISTRICT_SELECTION,
    NOTIFICATION_DISTRICT_SELECTION,
    REGISTERED,
    ASK_ABOUT_RENTING,
    RENTING,
    RENTING_OUT_SET_NAME,
    RENTING_SET_DESCRIPTION,
    RENTING_SET_PRICE,
    RENTING_OUT,
    RENTING_OUT_SET_PRICE,
    RENTING_OUT_SET_DESCRIPTION,
    RENTING_OUT_SELECT_CATEGORY,
    GET_MY_ADVERTS,
    GET_RENT_OUT_ADVERTS,
    RENTING_SET_NAME,
    RENTING_SELECT_CATEGORY,
    GET_RENT_ADVERTS
}
