package neighbors.enums.bot;

public enum State {
    NEW_USER,
    REGISTRATION,
    DISTRICT_SELECTION,
    NOTIFICATION_DISTRICT_SELECTION,
    REGISTERED,
    ASK_ABOUT_RENTING,
    RENTING,
    RENTING_SET_DESCRIPTION,
    RENTING_SET_PRICE,
    RENTING_OUT,
    RENTING_OUT_SET_PRICE,
    RENTING_OUT_SET_DESCRIPTION
}
