package neighbors.enums;

public enum State {
    NEW_USER,
    REGISTRATION,
    DISTRICT_SELECTION,
    NOTIFICATION_DISTRICT_SELECTION,
    REGISTERED,
    NOTIFICATIONS_ON,
    NOTIFICATIONS_OFF,
    RENTING,
    RENTING_OUT,
    RENTING_OUT_SET_PRICE
}
